"""user og

Revision ID: 27fb3aaca323
Revises: 4769a2c35a64
Create Date: 2024-06-03 15:45:12.739466

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27fb3aaca323"
down_revision = "4769a2c35a64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("og", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "og")
    # ### end Alembic commands ###
