"""channel invite link

Revision ID: 3c8fd3a7b139
Revises: 27fb3aaca323
Create Date: 2024-06-05 18:16:52.537135

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c8fd3a7b139"
down_revision = "27fb3aaca323"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("channel_invite_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "channel_invite_link")
    # ### end Alembic commands ###
