"""wallet_history

Revision ID: 4769a2c35a64
Revises: 51b72b053c46
Create Date: 2024-05-29 19:38:06.038695

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4769a2c35a64"
down_revision = "51b72b053c46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("history", sa.Column("wallet", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("history", "wallet")
    # ### end Alembic commands ###
