version: "3"

services:

  bot:
    build: .
    container_name: "sending-transaction_bot"
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/usr/src/bot

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis/data/:/data
