services:
  bot_wwb:
    image: ghcr.io/dryamvlad/wonnie-whale-bot:main
    container_name: "wonnie_whale_bot"
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - redis_wwb
    volumes:
      - .:/usr/src/bot

  redis_wwb:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis/data/:/data
